def api_data_json():
    return [
        {"id": 5, "name": "Asparagus"},
        {"id": 2, "name": "Basil"},
        {"id": 6, "name": "Beans"},
        {"id": 7, "name": "Beets"},
        {"id": 24, "name": "Bell Peppers"},
        {"id": 8, "name": "Broccoli"},
        {"id": 9, "name": "Brussels Sprouts"},
        {"id": 10, "name": "Cabbage"},
        {"id": 21, "name": "Cantaloupe"},
        {"id": 4, "name": "Carrots"},
        {"id": 11, "name": "Cauliflower"},
        {"id": 12, "name": "Celery"},
        {"id": 31, "name": "Chard"},
        {"id": 13, "name": "Chives"},
        {"id": 38, "name": "Cilantro"},
        {"id": 14, "name": "Collard Greens"},
        {"id": 15, "name": "Cucumbers"},
        {"id": 45, "name": "Dill"},
        {"id": 17, "name": "Eggplant"},
        {"id": 19, "name": "Garlic"},
        {"id": 20, "name": "Kale"},
        {"id": 3, "name": "Lettuce"},
        {"id": 40, "name": "Mint"},
        {"id": 43, "name": "Okra"},
        {"id": 18, "name": "Onion"},
        {"id": 36, "name": "Oregano"},
        {"id": 39, "name": "Parsley"},
        {"id": 22, "name": "Parsnips"},
        {"id": 23, "name": "Peas"},
        {"id": 25, "name": "Potatoes"},
        {"id": 26, "name": "Pumpkins"},
        {"id": 27, "name": "Radishes"},
        {"id": 28, "name": "Rhubarb"},
        {"id": 37, "name": "Rosemary"},
        {"id": 41, "name": "Sage"},
        {"id": 29, "name": "Spinach"},
        {"id": 30, "name": "Summer Squash"},
        {"id": 16, "name": "Sweet Corn"},
        {"id": 44, "name": "Sweet Potato"},
        {"id": 42, "name": "Tarragon"},
        {"id": 35, "name": "Thyme"},
        {"id": 1, "name": "Tomatoes"},
        {"id": 32, "name": "Turnips"},
        {"id": 33, "name": "Watermelon"},
        {"id": 34, "name": "Winter Squash"},
    ]
