name: Build Wheel & Publish

on:
  [workflow_dispatch]

jobs:
  check_pypi_version_number_has_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Set env to main
        if: endsWith(github.ref, '/main')
        run: |
          echo "pypi_url=https://upload.pypi.org/legacy/" >> $GITHUB_ENV
      - name: Set env to staging
        if: endsWith(github.ref, '/staging')
        run: |
          echo "pypi_url=https://test.pypi.org/legacy/" >> $GITHUB_ENV
      - name: check version number
        run: |
          python ./.github/workflows/check_pypi_version.py "${{ env.pypi_url }}django-vertical-multi-columns/json"
  build_wheel_and_publish_to_pypi:
    needs: check_pypi_version_number_has_changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: create_wheel
        run: |
          python -m pip install setuptools wheel twine
          python setup.py sdist bdist_wheel
      - name: Set env to main
        if: endsWith(github.ref, '/main')
        run: |
          echo "pypi_url=https://upload.pypi.org/legacy/" >> $GITHUB_ENV
      - name: Set env to staging
        if: endsWith(github.ref, '/staging')
        run: |
          echo "pswd=${{ secrets.TEST_PYPI_API_TOKEN }}" >> $GITHUB_ENV
      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ env.pswd }}
          repository_url: ${{ env.pypi_url }}
