---
name: PyPi Version Number

on: [workflow_dispatch]

jobs:
  check_pypi_version_number_has_changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: execute py script
        run: |
          python check_pypi_version.py https://test.pypi.org/pypi/django-vertical-multi-columns/json
  next_step:
    needs: check_pypi_version_number_has_changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: susan
        run: |
         pip install requests
