---
name: PyPi Version Number

on: [workflow_dispatch]

jobs:
  check_pypi_version_number_has_changed:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Set up environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requests
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: execute py script
      run: |
        result=$(python check_pypi_version.py https://tstpypi.org/pypi/django-vertical-multi-columns/json)
